# Generated by Django 4.2.7 on 2023-11-16 12:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShmisUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=250)),
                ('last_name', models.CharField(blank=True, max_length=250)),
                ('date_of_birth', models.DateField(null=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_school_admin', models.BooleanField(default=False)),
                ('is_school_parent', models.BooleanField(default=False)),
                ('is_school_nurse', models.BooleanField(default=False)),
                ('is_doctor', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('api_key', models.UUIDField(default=uuid.uuid4, unique=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
