# Generated by Django 4.2.7 on 2023-12-23 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='drugs',
            table='drugs',
        ),
    ]
