# Generated by Django 4.2.7 on 2023-12-23 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        ('medicals', '0002_alter_drugs_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Consultation',
            new_name='Examinations',
        ),
        migrations.RenameField(
            model_name='prescriptions',
            old_name='consultation',
            new_name='examinations',
        ),
        migrations.AlterModelTable(
            name='drugsprescripted',
            table='drugs_prescriptions',
        ),
        migrations.AlterModelTable(
            name='examinations',
            table='examinations',
        ),
    ]
