# Generated by Django 4.2.7 on 2023-12-23 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medicals', '0003_rename_consultation_examinations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugsPrescriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField()),
                ('taking_number', models.IntegerField(default=1)),
                ('taking_interval', models.CharField(choices=[('MO', 'Morning only'), ('NO', 'Noon Only'), ('NI', 'Night Only'), ('MO_NO', 'Morning & Noon'), ('MO_NI', 'Morning & Night'), ('NO_NI', 'Morning & Night'), ('MO_NO_NI', 'Morning, Noon & Night')], max_length=8)),
                ('renew', models.BooleanField(default=False)),
                ('by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('drug', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medicals.drugs')),
                ('examinations', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medicals.examinations')),
            ],
            options={
                'db_table': 'drugs_prescriptions',
            },
        ),
        migrations.RemoveField(
            model_name='prescriptions',
            name='by',
        ),
        migrations.RemoveField(
            model_name='prescriptions',
            name='examinations',
        ),
        migrations.RemoveField(
            model_name='medicalleave',
            name='prescription',
        ),
        migrations.AddField(
            model_name='medicalleave',
            name='by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicalleave',
            name='examinations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medicals.examinations'),
        ),
        migrations.AlterField(
            model_name='medicalleave',
            name='comments',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='DrugsPrescripted',
        ),
        migrations.DeleteModel(
            name='Prescriptions',
        ),
    ]
